apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-stg
  template:
    metadata:
      labels:
        app: my-app-stg
    spec:
      containers:
      - name: my-app
        image: localhost:5000/demoapp:v1.0-uat
